name: Build Run
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on: 
  workflow_dispatch:

jobs:
  Build-Job:
    timeout-minutes: 30
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: build-image
        uses: docker/build-push-action@v3
        with:
          context: .
          load: true
          build-args: |
            build_type=final
          tags: myimage:latest
          no-cache-filters: base,base-req-build
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: run-image
        run: |
          docker run -d --name runner -v $(pwd):/code myimage /code/test.py
          docker logs -f runner
          exit_code=$(docker inspect runner --format='{{.State.ExitCode}}')
          exit $((exit_code))
