name: Test Run

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: 
  workflow_dispatch:

env:
  DOMAIN: "thoughtfree.space"
  SUB_DOMAIN: "mail"
  DIGITALOCEAN_TOKEN: "${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}" 
  IP_ADDR: "0.0.0.0"

jobs:
  Test-Job:
    timeout-minutes: 30
    runs-on: ubuntu-22.04
    steps:
      - name: change dns record
        run: |
          touch headers_file
          echo "Authorization: Bearer $DIGITALOCEAN_TOKEN" >> headers_file
          export rec_id=$(curl -H @headers_file "https://api.digitalocean.com/v2/domains/${DOMAIN}/records" | jq --arg sd "$SUB_DOMAIN" '.domain_records[] | select(.name=="$sd") | .id')
          echo "rec: $rec_id"
          echo "Content-Type: application/json" >> headers_file
          curl -X PATCH -H @headers_file --data "{ \"data\": \"${IP_ADDR}\" }" "https://api.digitalocean.com/v2/domains/$DOMAIN/records/$rec_id"


      
