name: Test Run

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: 
  workflow_dispatch:

env:
  DOMAIN: "thoughtfree.space"
  SUB_DOMAIN: "mail"
  DIGITALOCEAN_TOKEN: "${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}" 
  IP_ADDR: "0.0.0.0"

jobs:
  Test-Job:
    timeout-minutes: 30
    runs-on: ubuntu-22.04
    steps:
      - name: change dns record
        run: |
          touch headers_file
          #print "Content-Type: application/json" >> headers_file
          print "Authorization: Bearer $DIGITALOCEAN_TOKEN" >> headers_file
          curl -H @headers_file https://api.digitalocean.com/v2/domains/${DOMAIN}/records 
          #rec_id=$(curl -X GET -H @headers_file "https://api.digitalocean.com/v2/domains/${DOMAIN}/records" | jq --arg sd "$SUB_DOMAIN" '.domain_records[] | select(.name=="$sd") | .id')
          #curl -X PATCH $headers --data "{ \"data\": \"${IP_ADDR}\" }" "https://api.digitalocean.com/v2/domains/$DOMAIN/records/$rec_id"


      
