name: Test Run

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: 
  workflow_dispatch:

env:
  RELEASE: dummy 

jobs:
  Test-Job:
    timeout-minutes: 30
    runs-on: ubuntu-22.04
    steps:
      - name: Make a release
        run: |
          touch asset.txt
          rand=$RANDOM
          for i in {1..50000}
          do
            echo "blah $rand $i" >> asset.txt
            echo >> asset.txt
          done
      - name: List Releases
        id: list-releases
        uses: github-actions-tools/gh-list-releases@main

      - name: Check Release
        id: release-check
        run: |
          set +e
          echo '${{ steps.list-releases.outputs.releases }}' | jq '.[]' | grep -q "$RELEASE"
          has_release=$?
          set -e
          if [[ $has_release ]]; then
            echo "::set-output name=hasrelease::yes"
          else
            echo "::set-output name=hasrelease::no"
          fi
      - name: Create Release
        id: create-release
        if: ${{ steps.release-check.outputs.hasrelease }} == "no"
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "${{ env.RELEASE }}"
          files: asset.txt
      
