name: Test Run

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: 
  workflow_dispatch:

jobs:
  Test-Job:
    timeout-minutes: 30
    runs-on: ubuntu-22.04
    steps:
      - name: Make a release
        run: |
          touch asset.txt
          for i in {1..50000}
          do
            echo "blah $i" >> asset.txt
            echo >> asset.txt
          done
      - name: List Releases
        id: list-releases
        uses: github-actions-tools/gh-list-releases@main

      - name: Create Release
        run: |
          echo '${{ steps.list-releases.outputs.releases }}'

      
