name: Test Run

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: 
  workflow_dispatch:


jobs:
  Test-Job:
    timeout-minutes: 30
    runs-on: ubuntu-22.04
    steps:

      - name: Get current date
        run: echo "date=$(date +'%d%b%Y %H:%M:%S')" >> $GITHUB_OUTPUT
        id: date

      - name: Get Random
        run:  echo "rand=$RANDOM" >> $GITHUB_OUTPUT
        id: random

      - uses: actions/checkout@v3

      - name: Create assets
        run: |
          touch asset1.txt
          export rand="${{ steps.random.outputs.rand }}"
          for i in {1..50000}
          do
            echo "blah1 $rand $i" >> asset1.txt
            echo >> asset1.txt
          done
          touch asset2.txt
          export rand="${{ steps.random.outputs.rand }}"
          for i in {1..50000}
          do
            echo "blah2 $rand $i" >> asset2.txt
            echo >> asset2.txt
          done


      - name: Make release
        uses: ./.github/actions/releaser
        with:
          name: test release name
          tag_name: test-release
          assets: |
            asset1.txt
            asset2.txt
          body: "testing things ${{ steps.random.outputs.rand }}"
          gh_token: ${{ secrets.github_token }}
